baseURL = "https://golfed.xyz/"
title = "golfed.xyz"

theme = "nightfall"
languageCode = "en-GB"
enableRobotsTXT = true
rssLimit = 20

[author]
    name = "Arttu Einistö"
    email = "arttu@golfed.xyz"

[menu]

[[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[[menu.header]]
    name = "posts"
    weight = 0
    url = "posts"

[[menu.header]]
    name = "projects"
    weight = 0
    url = "projects"

[[params.social]]
    key = 1
    name = "github"
    url = "https://github.com/17ms"

[[params.social]]
    key = 2
    name = "email"
    url = "mailto:arttu@golfed.xyz"

[[params.social]]
    key = 3
    name = "linkedin"
    url = "https://linkedin.com/in/einisto/"
